### ISSUE TITLE
NMSE gave me the following: thread resume failed

### ISSUE THREAD

**Issue by fr33soul** [Ant2888/NMSExtender#10]
I tryed multiple times to run NMSE and the result is always the same:

thread resume failed

Win10+steam

**Comment by Ant2888** [comment]
This issue was very poorly described. In the future please put more effort into them or I will in general just close them. 

By poorly described I mean you forgot to mention: The game crashed BEFORE it said thread resume failed, and You are running the experimental version of the game. 

And although it is not relevant to THIS particular problem, whether you're using shaders is appreciated.

It is fixed though. The experimental version deleted an entire function from the game that I was hooking into so the pattern scan would not work.

**Comment by fr33soul** [comment]
this means that experimental version is not compatible with NMSE?

**Comment by fr33soul** [comment]
how can i know if the game crashed BEFORE it said thread resume failed? it doesnt even start!
And also i didnt see in the description of NMSE that is not compatible with experimental version, so i think that POOR description is yours..

**Comment by Ant2888** [comment]
A mod supporting a version of a game that is not publicly released would be more of a surprise than the reverse. 

Regardless that wasn't the point! For an effective issue please post all the details you can think, everything matters!
