### ISSUE TITLE
Move Upgrades

### ISSUE THREAD

**Issue by eeg710** [Ant2888/NMSExtender#17]
Is there any way you can incorporate a feature that we could move upgrades from one place to another in the exosuit, ship, and multi-tool?

**Comment by Ant2888** [comment]
Yes. Right now it is currently not mapped out but with some simple patching and such I'm sure NMSE would very easily trivialize it. 

Currently a bit busy but when I get to mapping out the inventories I could make the mod very quickly. You could try to get someone to make the mod in the mean time!

**Comment by tehsaccade** [comment]
This is an issue I am working on - the ability to transpose items of the same "size" between ship and suit and also without the need for a free slot to swap position of, eg, a gravatino ball and antimatter, move all weapons/warp upgrades into the same areas - it is a related issue.

It would be good to be able to put all shields next to the iron to recharge them on ship, for example.
And all the life support extras, in line with titanium, etc... for recharge.

I don't see why this isn't possible and I don't see why it ought to have to be a mod when it is a feature the game could do with, to improve it.

Atm - the only way to move upgrades is to remove them and rebuild them (gives you some reason to keep playing...) or do what I do and plan ahead for the upgrades you will be using building them in the "right" place, ahead of time.

//Problem is, the "size" or "capacity" of materials in ship to exosuit is different, so it creates a problem - I am still trying to understand how it works.  Once I figure item transpose position, I think that module transpose position ought to be similar, eeg710.

//It won't be happening soon - it's lower on my list of priorities than increasing the hostility of the enviornment of the game in terms of sentinals, their "reinforcement" timers for "combat/elite" (elite? is that a joke? Even the walkers are no challenge...), how stupid the AI is, how "food chain" does not contain enough predators in relation to grazers, in relation to minerals present, etc... 

//Requires what almost could be considered "total conversion" mod, if you include the other changes and the alternative reskins (not simply replacements) for variety among existing models and random chance alterations in favour of hostile encounters, eg space battles... The game is too "clean". I want my ships to look "dirtier" - not freshly painted polygons - I also want to rename my ship without renaming EVERY ship of that type... 

//The universe is too easy to survive. Death means nothing. 120 hours later, still alive and - there is no challenge. Even 15 enemy ships distress call, plus sentinal ships from stray hit on container (come on... really?) - no death.

//only death I experience in the game is falling asleep and life support running out, because the diurnal cycle and light makes me drowsy (not to mention the lack of action and repetitive collecting/crafting routine to continue exploration.

//digressed a bit here - but - it's something I'm looking into, eeg710.
